--- Question: What is the total revenue made per store?
/* Answer*/

SELECT S.StoreID, S.StoreName, SUM(P.UnitPrice*T.Quantity*(1-T.Discount)) AS TotalSales
FROM store S
JOIN transaction T
ON S.StoreID = T.StoreID
JOIN product P
ON P.ProductID = T.ProductID
GROUP BY S.StoreID,S.StoreName
ORDER BY TotalSales DESC;


--- Question: What is the total profit made per store?
/* Answer*/

SELECT S.StoreID, S.StoreName,SUM(P.UnitPrice*T.Quantity*(1-T.Discount) -(P.CostPrice*T.Quantity))
AS TotalProfit
FROM store S
JOIN transaction T
ON S.StoreID = T.StoreID
JOIN product P
ON P.ProductID = T.ProductID
GROUP BY S.StoreID,S.StoreName
ORDER BY TotalProfit DESC;


--- Question: What is the total profit made per products?
/* Answer*/

SELECT P.ProductID,P.ProductName,SUM(P.UnitPrice*T.Quantity*(1-T.Discount) -(P.CostPrice*T.Quantity))
AS TotalProfit
FROM Product P
JOIN transaction T
ON P.ProductID = T.ProductID
GROUP BY P.ProductID,P.ProductName
ORDER BY TotalProfit DESC;



--- Question: What is the profit margin generated by each products?
/* Answer*/

SELECT P.ProductID,P.ProductName,SUM(T.Quantity) AS Quantity_Sold, 
SUM(P.UnitPrice*T.Quantity*(1-T.Discount)) AS Total_Sales,
SUM(P.UnitPrice*T.Quantity*(1-T.Discount) -(P.CostPrice*T.Quantity))
AS Total_Profit,
SUM(P.UnitPrice*T.Quantity*(1-T.Discount) -(P.CostPrice*T.Quantity))/ SUM(P.UnitPrice*T.Quantity*(1-T.Discount))*100
AS Profit_Margin
FROM Product P
JOIN transaction T
ON P.ProductID = T.ProductID
GROUP BY P.ProductID,P.ProductName
ORDER BY Total_Profit DESC;



-- Question: How many products fall into each profit margin category?
/* Answer*/

With Product_Margin AS (SELECT P.ProductID,P.ProductName,
SUM(P.UnitPrice*T.Quantity*(1-T.Discount) -(P.CostPrice*T.Quantity))/ SUM(P.UnitPrice*T.Quantity*(1-T.Discount))*100
AS Profit_Margin
FROM Product P
JOIN transaction T
ON P.ProductID = T.ProductID
GROUP BY P.ProductID,P.ProductName
)
SELECT
CASE 
   WHEN Profit_Margin BETWEEN 36 AND 45 THEN 'High Margin'
   WHEN Profit_Margin BETWEEN 26 and 35 THEN 'Medium Margin'
   ELSE 'Low Margin'
   END AS Margin_Category,
 COUNT(*) AS Products
FROM Product_Margin
GROUP BY Margin_Category;



--- Question: How many units are sold per margin category?
/* Answer*/

With Product_Margin AS (SELECT P.ProductID,P.ProductName,SUM(T.Quantity) AS Total_Quantity,
SUM(P.UnitPrice*T.Quantity*(1-T.Discount) -(P.CostPrice*T.Quantity))
AS Total_Profit,
SUM(P.UnitPrice*T.Quantity*(1-T.Discount) -(P.CostPrice*T.Quantity))/ SUM(P.UnitPrice*T.Quantity*(1-T.Discount))*100
AS Profit_Margin
FROM Product P
JOIN transaction T
ON P.ProductID = T.ProductID
GROUP BY P.ProductID,P.ProductName
)
SELECT
CASE 
   WHEN Profit_Margin BETWEEN 36 AND 45 THEN 'High Margin'
   WHEN Profit_Margin BETWEEN 26 and 35 THEN 'Medium Margin'
   ELSE 'Low Margin'
   END AS Margin_Category,
 SUM(Total_Quantity) AS Quantity, SUM(Total_Profit) AS Profit_per_Margin
FROM Product_Margin
GROUP BY Margin_Category
ORDER BY Margin_Category DESC;




--- Question: What category does each disount on products falls?
/* Answer*/

SELECT S.StoreName, P.ProductID, P.ProductName,T.Discount*100 as Discount,
CASE 
   WHEN T.Discount*100 BETWEEN 1 AND 10 THEN 'Low Discount'
   WHEN T.Discount*100 BETWEEN 11 AND 20 THEN 'Medium Discount'
   WHEN T.Discount*100 > 20 THEN 'High Discount'
   ELSE 'No Discount'  
   END AS Discount_Category
FROM Product P
JOIN Transaction T
ON P.ProductID = T.ProductID
JOIN Store S
ON T.StoreID = S.StoreID
GROUP BY S.StoreName, P.ProductID, T.Discount


--- Question: What percentage does low profit margin takes?
/* Answer*/

WITH Store_Product AS (
  SELECT
       S.StoreID, S.StoreName, P.ProductID, SUM(T.Quantity) AS Total_Quantity,
	   AVG(T.Discount) AS Avg_Discount, 
	   SUM(P.UnitPrice*T.Quantity*(1-T.Discount) -(P.CostPrice*T.Quantity))/ SUM(P.UnitPrice*T.Quantity*(1-T.Discount))*100
AS Profit_Margin
FROM Store S
JOIN Transaction T 
ON S.StoreID = T.StoreID
JOIN Product P
ON T.ProductID = P.ProductID
GROUP BY S.StoreID, S.StoreName, P.ProductID
),
Margin_Category AS (
SELECT*,
    CASE
	   WHEN Profit_Margin BETWEEN 36 AND 45 THEN 'High Margin'
	   WHEN Profit_Margin BETWEEN 26 AND 35 THEN 'Medium Margin'
	   ELSE 'Low'
	   END AS Margin_Category
FROM Store_Product
)
SELECT
    StoreID, StoreName, AVG(Avg_Discount)*100 AS Avg_Discount,
	SUM(CASE WHEN Margin_Category = 'Low' THEN Total_Quantity ELSE 0 END ) AS Low_Margin_Qty,
	SUM(Total_Quantity) AS Total_Qty,
	(SUM(CASE WHEN Margin_Category = 'Low' THEN Total_Quantity ELSE 0 END)*100 / SUM(Total_Quantity)) 
	AS Low_Margin_Percentage
FROM Margin_Category
GROUP BY StoreID, StoreName
ORDER BY Avg_Discount DESC;




-- Question: How does discount affect profitability?
/* Answer*/

--- Based on discount category

SELECT 
    CASE 
        WHEN T.Discount = 0 THEN 'No Discount'
        WHEN T.Discount BETWEEN 0.01 AND 0.10 THEN 'Low Discount'
        WHEN T.Discount BETWEEN 0.11 AND 0.20 THEN 'Medium Discount'
        ELSE 'High Discount'
    END AS Discount_Level,
	AVG( (P.UnitPrice*T.Quantity*(1-T.Discount) - (P.CostPrice*T.Quantity)) 
        / (P.UnitPrice*T.Quantity*(1-T.Discount)) * 100
    ) AS Avg_Profit_Margin

FROM Transaction T
JOIN Product P ON T.ProductID = P.ProductID

GROUP BY Discount_Level
ORDER BY Avg_Profit_Margin DESC;


--- Store Level

SELECT 
    S.StoreID,
    S.StoreName,
    AVG(T.Discount)*100 AS Avg_Discount,

    SUM(P.UnitPrice*T.Quantity*(1-T.Discount) - (P.CostPrice*T.Quantity)) 
    / SUM(P.UnitPrice*T.Quantity*(1-T.Discount)) * 100 AS Profit_Margin

FROM Store S
JOIN Transaction T ON S.StoreID = T.StoreID
JOIN Product P ON T.ProductID = P.ProductID

GROUP BY S.StoreID, S.StoreName
ORDER BY Avg_Discount DESC;
